---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

client_rb:
  treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux-2
    driver_config:
      box: ywatase/amzn2
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: opensuse-leap-15
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: client
    run_list:
      - recipe[test::client]
  - name: server
    run_list:
      - recipe[test::server]
